SELECT MAX(AMOUNT),MIN(AMOUNT),COUNT(AMOUNT),SUM(AMOUNT),AVG(AMOUNT) FROM SALES

SELECT* FROM SALES ORDER BY TOTALPRICE

SELECT MAX(AMOUNT),MIN(AMOUNT),COUNT(AMOUNT),SUM(AMOUNT),AVG(AMOUNT) FROM SALES
WHERE CITY='ANKARA'

SELECT MAX(AMOUNT),MIN(AMOUNT),COUNT(AMOUNT),SUM(AMOUNT),AVG(AMOUNT) FROM SALES
WHERE CITY='ÝSTANBUL'

SELECT CITY,
MAX(AMOUNT) AS MAXPRICE,
MIN(AMOUNT) AS MINPRICE ,
COUNT(AMOUNT) AS ROWCOUNT_,
SUM(AMOUNT) AS TOTALPRICE,
AVG(AMOUNT) AS AVGPRICE FROM SALES
GROUP BY CITY

SELECT TOP 10
    CITY,
    SUM(TOTALPRICE) AS TOTALPRICE
FROM SALES
GROUP BY CITY
ORDER BY TOTALPRICE DESC;

