-- GÜN BAZLI SATIÞ RAKAMLARI HEAPLANMASI/CALCULATION OF DAY-BASED SALES FIGURES.
SELECT *,
CONVERT(DATE,DATE_) AS DATE2
FROM SALES WHERE CITY='ANKARA'
ORDER BY DATE_
-----------------------------------------------
SELECT CONVERT(DATETIME,'2019-01-01 08:46:10.000')
--DATETIME , TIME ,DATE
-----------------------------------------------
SELECT *
FROM SALES WHERE CITY='ANKARA'
ORDER BY DATE_
UPDATE SALES SET DATE2= CONVERT (DATE,DATE_)
-----------------------------------------------
SELECT*
FROM SALES WHERE CITY='ANKARA'
AND DATE2='2019-01-01 00:00:00'
ORDER BY DATE_
-----------------------------------------------
SELECT CITY,DATE2,SUM(TOTALPRICE) AS TOTALPRICE
FROM SALES WHERE CITY='ANKARA'
GROUP BY CITY,DATE2
ORDER BY CITY,DATE2 DESC
-----------------------------------------------
SELECT DATE2,CITY,SUM(TOTALPRICE) AS TOTALPRICE FROM SALES
WHERE DATE2='2019-01-01'
GROUP BY DATE2,CITY
ORDER BY DATE2,SUM(TOTALPRICE) DESC
-----------------------------------------------
SELECT MONTHNAME_, CITY,SUM(TOTALPRICE) AS TOTALPRICE
FROM SALES
GROUP BY CITY,MONTHNAME_
ORDER BY MONTHNAME_,SUM(TOTALPRICE) DESC
-----------------------------------------------
SELECT [CATEGORY1],[CATEGORY2],[CATEGORY3],[CATEGORY4],
SUM(TOTALPRICE) AS TOTALPRICE,
COUNT(*) AS ROWCOUNT_,
SUM(AMOUNT) AS TOTALAMOUNT

FROM SALES
GROUP BY [CATEGORY1],[CATEGORY2],[CATEGORY3],[CATEGORY4]
ORDER BY [CATEGORY1],[CATEGORY2],[CATEGORY3],[CATEGORY4]
-----------------------------------------------
SELECT FICHENO,COUNT(*) FROM SALES
WHERE MONTHNAME_='01.OCAK'
AND CITY='ADANA'
GROUP BY FICHENO
ORDER BY [CATEGORY1],[CATEGORY2],[CATEGORY3],[CATEGORY4]
-----------------------------------------------
SELECT CITY,COUNT( DISTINCT [CUSTOMERNAME]) AS [CUSTOMERNAME],COUNT( DISTINCT FICHENO) AS FICHENO ,COUNT(*) FROM SALES 
WHERE MONTHNAME_='01.OCAK'
GROUP BY CITY
ORDER BY CITY
-----------------------------------------------
SELECT CITY,SUM(TOTALPRICE)

FROM SALES GROUP BY CITY
HAVING SUM(TOTALPRICE)<40000
ORDER BY SUM(TOTALPRICE) DESC
-----------------------------------------------
SELECT CITY,SUM(TOTALPRICE)

FROM SALES
WHERE CITY IN ('ANKARA','ÝSTANBUL','ÝZMÝR','AYDIN','HATAY')
GROUP BY CITY
HAVING SUM(TOTALPRICE)<40000
ORDER BY SUM(TOTALPRICE) DESC
-----------------------------------------------
