SELECT * FROM CUSTOMERS
ORDER BY ID ASC
--SIRALAMALARDA ASC=ASCENDÝNG YANÝ ARTAN SIRALAMA
SELECT * FROM CUSTOMERS
ORDER BY City DESC
-- HARFLERDE Z>A ÞEKLÝNDE DEVAM EDER.
----SIRALAMALARDA DESC=DESCENDÝNG YANÝ AZALAN SIRALAMA

SELECT*FROM CUSTOMERS
ORDER BY City ASC,Costumer_Name DESC
-- ÖNCE ÞEHÝRLERÝ SIRALAR  ALFABETÝK SIRADA SONRASINDA MÜÞTERÝ ÝSÝMLERÝNÝ SIRALAR 

SELECT*FROM CUSTOMERS
WHERE Gender='KADIN'
ORDER BY City ASC,Costumer_Name DESC

SELECT*FROM CUSTOMERS
ORDER BY 2
--ORDER BY DAN SONRA YAZILAN SAYIYA GÖRE O SÜTUNA GÖRE SIRALAR.