SELECT * FROM CUSTOMERS

WHERE City IN ('iSTANBUL','ANKARA','ÝZMÝR')
UPDATE CUSTOMERS SET GENDER='KADIN' WHERE GENDER='K'
UPDATE CUSTOMERS SET GENDER='ERKEK' WHERE GENDER='E'
DELETE FROM CUSTOMERS WHERE ID=18

SELECT * FROM CUSTOMERS
WHERE  City='iSTANBUL' AND District='BEÞÝKTAÞ'

SELECT * FROM CUSTOMERS
WHERE Gender='ERKEK' OR 22>Age

SELECT * FROM CUSTOMERS
WHERE Gender='ERKEK' OR Birthdate BETWEEN '19900101' AND '20000101'